### ISSUE TITLE
Monkey-patch typo that removes TitleIndex get_urls method permanently

### ISSUE THREAD

**Issue by DmitriySelischev** [nephila/djangocms-apphook-setup#9]
In [This commit](https://github.com/nephila/djangocms-apphook-setup/commit/8433a60399d7a539303e81c604326a1c99981899#diff-8933cae28191a53420a8353bb2994068) you reimplemented base.py file that contains monkey-patching for TitleIndex. In the previous version, you always return original get_url method, BUT in a current version, you have tabbed returning of original method INSIDE if statement that checks if pages with apphook don't exist.
I'll provide a pull request for fixing that issue.
And also, please provide hard versions between djangocms_blog and djangocms-apphook-setup.

**Comment by yakky** [comment]
Thanks @DmitriySelischev !
I will have a look at this issue and the pull request shortly

**Comment by yakky** [comment]
PR looks good, please rebase after the merge of #11 
Regarding the version pinning, this will be doable after the djangocms-blog 0.9 release when we will drop django CMS < 3.4 and we will be able to pin >= 0.3 (0.3.1 actually)

**Comment by zibertscrem** [comment]
Any chance that pull request to be accepted?

**Comment by antwertinger** [comment]
I have the same issue, the pull request solved the problem. Please accept it

**Comment by yakky** [comment]
@zibertscrem @antwertinger sorry everyone, in the end the PR got lost in the notification noise
After merging #12 to let test run and to have an up-to-date project setup, I will merge it

**Comment by yakky** [comment]
Fixed in #10 
An updated release will follow shortly

**Comment by yakky** [comment]
@zibertscrem @antwertinger released 0.4.1  which includes the fix for this issue. Sorry it took so long to make it available
